spring.application.name=website
server.port=8081

# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/website_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate ve JPA Ayarları
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true