spring.application.name=website
server.port=8081

# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/website_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate ve JPA Ayarları
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# E-Posta (JavaMailSender) Ayarları
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ysfulgen142@gmail.com
spring.mail.password=klql yojg olcd lvil
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin Giriş Bilgileri
spring.security.user.name=root
spring.security.user.password=root

# JWT Güvenlik Anahtarı
jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290IiwiaWF0IjoxNzcyMDE5OTkxLCJleHAiOjE3NzIwNjMxOTF9.Ocu4nM3S6BpFoxNQc4tuQUD9wpMmfGKxJzDppHOea98
