# --- SUNUCU AYARLARI ---
spring.application.name=website
server.port=${PORT:8080}
spring.main.allow-bean-definition-overriding=true


# --- POSTGRESQL VERİTABANI BAĞLANTISI ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/website_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE VE JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- E-POSTA AYARLARI ---
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:ysfulgen142@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# JWT Şifreleme Anahtarı
jwt.secret=${JWT_SECRET:yusuf_ulgen_cok_gizli_ozel_anahtar_2026_backend_test_key_123456}

# Token'ın geçerlilik süresi (Milisaniye cinsinden. 86400000 = 1 Gün)
jwt.expiration=86400000

# (Varsayılan Spring Security girişini kapatıyoruz çünkü kendi JWT Login'imizi yazacağız)
spring.security.user.name=${ADMIN_USERNAME:root}
spring.security.user.password=${ADMIN_PASSWORD:root}