# --- SUNUCU AYARLARI ---
spring.application.name=website
server.port=8081

# --- POSTGRESQL VERİTABANI BAĞLANTISI ---
spring.datasource.url=jdbc:postgresql://localhost:5432/website_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE VE JPA (TABLO OLUŞTURUCU) ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- E-POSTA AYARLARI (GİZLİ TUTULMALIDIR!) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ysfulgen142@gmail.com
spring.mail.password=klql yojg olcd lvil
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Şifreleme Anahtarı (Minimum 256-bit olmalı, seninki gayet uzun ve güvenli)
jwt.secret=yusuf_ulgen_cok_gizli_ozel_anahtar_2026_backend_test_key_123456

# Token'ın geçerlilik süresi (Milisaniye cinsinden. Örn: 86400000 = 1 Gün)
jwt.expiration=86400000

# (Varsayılan Spring Security girişini kapatıyoruz çünkü kendi JWT Login'imizi yazacağız)
spring.security.user.name=root
spring.security.user.password=root